Fix chown
PrestaShopCorp/ps_eventbus pull request #225
Opened 2024-01-15 15:46 UTC by jokesterfr

2024-01-16 10:33 UTC, Clap404 requested changes

2024-01-16 10:33 UTC, Clap404 commented on e2e-env/init-scripts/install-module.sh
> +  sudo -g www-data -u www-data -- "$@"
J'ai un problème avec ce sudo : le script est exécuté en tant que www-data et pas root, donc ```run_user``` échoue.

2024-01-16 11:00 UTC, jokesterfr commented on e2e-env/init-scripts/install-module.sh
> +  sudo -g www-data -u www-data -- "$@"
ah c'est pourtant la variable `INIT_SCRIPTS_USER=root` qui est mise dans le docker-compose.yml, et donc théoriquement on devrait lancer l'exécution de ./install-module.sh en root non ?
@Clap404

2024-01-17 15:29 UTC, Clap404 commented on e2e-env/init-scripts/install-module.sh
> +  sudo -g www-data -u www-data -- "$@"
bug fix dans prestashop-flashlight : https://github.com/PrestaShop/prestashop-flashlight/pull/65

2024-02-07 17:38 UTC, merged